apiVersion: v1	
kind: Service	
metadata:	
  name: guestbook-ui
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: random
spec:	
  ports:	
  - port: 80	
    targetPort: 80	
  selector:	
    app: guestbook-ui
